package test_exception

import (
	"testing"
)

func TestBaseException(t *testing.T) {

	return
}
